//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'player_error_reasons.g.dart';

class PlayerErrorReasons extends EnumClass {

  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'NO_PREV_TRACK')
  static const PlayerErrorReasons NO_PREV_TRACK = _$NO_PREV_TRACK;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'NO_NEXT_TRACK')
  static const PlayerErrorReasons NO_NEXT_TRACK = _$NO_NEXT_TRACK;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'NO_SPECIFIC_TRACK')
  static const PlayerErrorReasons NO_SPECIFIC_TRACK = _$NO_SPECIFIC_TRACK;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'ALREADY_PAUSED')
  static const PlayerErrorReasons ALREADY_PAUSED = _$ALREADY_PAUSED;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'NOT_PAUSED')
  static const PlayerErrorReasons NOT_PAUSED = _$NOT_PAUSED;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'NOT_PLAYING_LOCALLY')
  static const PlayerErrorReasons NOT_PLAYING_LOCALLY = _$NOT_PLAYING_LOCALLY;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'NOT_PLAYING_TRACK')
  static const PlayerErrorReasons NOT_PLAYING_TRACK = _$NOT_PLAYING_TRACK;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'NOT_PLAYING_CONTEXT')
  static const PlayerErrorReasons NOT_PLAYING_CONTEXT = _$NOT_PLAYING_CONTEXT;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'ENDLESS_CONTEXT')
  static const PlayerErrorReasons ENDLESS_CONTEXT = _$ENDLESS_CONTEXT;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'CONTEXT_DISALLOW')
  static const PlayerErrorReasons CONTEXT_DISALLOW = _$CONTEXT_DISALLOW;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'ALREADY_PLAYING')
  static const PlayerErrorReasons ALREADY_PLAYING = _$ALREADY_PLAYING;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'RATE_LIMITED')
  static const PlayerErrorReasons RATE_LIMITED = _$RATE_LIMITED;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'REMOTE_CONTROL_DISALLOW')
  static const PlayerErrorReasons REMOTE_CONTROL_DISALLOW = _$REMOTE_CONTROL_DISALLOW;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'DEVICE_NOT_CONTROLLABLE')
  static const PlayerErrorReasons DEVICE_NOT_CONTROLLABLE = _$DEVICE_NOT_CONTROLLABLE;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'VOLUME_CONTROL_DISALLOW')
  static const PlayerErrorReasons VOLUME_CONTROL_DISALLOW = _$VOLUME_CONTROL_DISALLOW;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'NO_ACTIVE_DEVICE')
  static const PlayerErrorReasons NO_ACTIVE_DEVICE = _$NO_ACTIVE_DEVICE;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'PREMIUM_REQUIRED')
  static const PlayerErrorReasons PREMIUM_REQUIRED = _$PREMIUM_REQUIRED;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'UNKNOWN')
  static const PlayerErrorReasons UNKNOWN = _$UNKNOWN;
  /// * `NO_PREV_TRACK` - The command requires a previous track, but there is none in the context. * `NO_NEXT_TRACK` - The command requires a next track, but there is none in the context. * `NO_SPECIFIC_TRACK` - The requested track does not exist. * `ALREADY_PAUSED` - The command requires playback to not be paused. * `NOT_PAUSED` - The command requires playback to be paused. * `NOT_PLAYING_LOCALLY` - The command requires playback on the local device. * `NOT_PLAYING_TRACK` - The command requires that a track is currently playing. * `NOT_PLAYING_CONTEXT` - The command requires that a context is currently playing. * `ENDLESS_CONTEXT` - The shuffle command cannot be applied on an endless context. * `CONTEXT_DISALLOW` - The command could not be performed on the context. * `ALREADY_PLAYING` - The track should not be restarted if the same track and context is already playing, and there is a resume point. * `RATE_LIMITED` - The user is rate limited due to too frequent track play, also known as cat-on-the-keyboard spamming. * `REMOTE_CONTROL_DISALLOW` - The context cannot be remote-controlled. * `DEVICE_NOT_CONTROLLABLE` - Not possible to remote control the device. * `VOLUME_CONTROL_DISALLOW` - Not possible to remote control the device's volume. * `NO_ACTIVE_DEVICE` - Requires an active device and the user has none. * `PREMIUM_REQUIRED` - The request is prohibited for non-premium users. * `UNKNOWN` - Certain actions are restricted because of unknown reasons. 
  @BuiltValueEnumConst(wireName: r'unknown_default_open_api', fallback: true)
  static const PlayerErrorReasons unknownDefaultOpenApi = _$unknownDefaultOpenApi;

  static Serializer<PlayerErrorReasons> get serializer => _$playerErrorReasonsSerializer;

  const PlayerErrorReasons._(String name): super(name);

  static BuiltSet<PlayerErrorReasons> get values => _$values;
  static PlayerErrorReasons valueOf(String name) => _$valueOf(name);
}

/// Optionally, enum_class can generate a mixin to go with your enum for use
/// with Angular. It exposes your enum constants as getters. So, if you mix it
/// in to your Dart component class, the values become available to the
/// corresponding Angular template.
///
/// Trigger mixin generation by writing a line like this one next to your enum.
abstract class PlayerErrorReasonsMixin = Object with _$PlayerErrorReasonsMixin;

